model_path: "./model/captcha_lenet"
img_size: 28
dataset_path: "./data"

prepare: 
  solved_path: "./dataset/Captcha Solver/solved-captchas/electoral-tagged"

train:
  lr: 0.001
  epochs: 2
  batch_size: 128

predict:
  test_data_path: "./dataset/Captcha Solver/unsolved-captchas/electoral-tagged"
  out_path: "./data/predicted"